### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by cwwise** [yaolaiyaoqu/iso8583#1]
使用这个函数

```
int iso8583_unpack(struct iso8583 *handle, unsigned char *data, unsigned int *size)
```

size的作用是什么？

```
static inline int to_userdata(struct iso8583 *handle, unsigned int index, unsigned char *data, unsigned int *size)
```

这个函数 作用是什么？
自己对c语言了解的很基础。
谢谢了。

**Comment by yaolaiyaoqu** [comment]
这个调用的时候传进去 buf的长度， 如果buf不够长函数就报错了。
比如 
size = 20
iso8583_unpack(handle, data, &size)
如果里面解到第20个字符还没有解完就报错了。

如果解成功，返回iso8583报文的长度。
比如解到16个字节就解完了，size这个时候的值是16.

to_userdata 这个是解包的时候把8583里面的数据提出来放到每个域里面的，
比如刚好解到第4域了，就将第4域的内容copy到第4域的buf中。
